apiVersion: apps/v1
#apiVersion: extensions/v1
kind: Deployment
metadata:
  name: {{ include "caylent.fullname" . }}
  labels:
    {{- include "caylent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "caylent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "caylent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "caylent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            # HELM_SECRET Environment variable will hold the unencrypted value of the secret event-secret
            - name: HELM_SECRET
              valueFrom:
                secretKeyRef:
                  name: event-secret
                  key: my_secret_key
            # ENVIRONMENT VARIABLE
            - name: ENVIRONMENT
              value: {{ .Values.environment_caylent }} 
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
