apiVersion: v1
kind: Secret
metadata:
  name: event-secret
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  #my_secret_key: {{ .Values.secret_challenge_caylent | replace ":" "" | b64enc | quote }}
  my_secret_key: {{ .Values.secret_challenge_caylent | b64enc | quote }}
