{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "caylent.serviceAccountName" . }}
  labels:
{{ include "caylent.labels" . | nindent 4 }}
{{- end -}}
